@echo off
echo [i] Killing explorer ...
taskkill /im explorer.exe /f
echo [i] Removing old version ...
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe /u %~dp0SigningProperty\SigningProperty\bin\Debug\SigningProperty.dll
echo [i] Installing to GAC ...
gacutil -i %~dp0SigningProperty/bin/Debug/SigningProperty.dll
echo [i] Registering ...
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\RegAsm.exe /codebase %~dp0SigningProperty\bin\Debug\SigningProperty.dll
echo [i] Restarting Explorer ...
start explorer.exe
exit